import type { MonthLedger } from "@/lib/finance/types";

export function createSampleLedger(monthKey: string): MonthLedger {
  return {
    monthKey,
    incomeCents: 720000,
    items: [
      {
        id: "rent",
        section: "fixed",
        category: "Housing",
        name: "Rent",
        budgetCents: 240000,
        actualCents: 240000,
        dueDay: 1,
        verified: true,
        sortOrder: 1,
        metadata: { recurring: true },
      },
      {
        id: "power",
        section: "fixed",
        category: "Utilities",
        name: "PG&E",
        budgetCents: 18000,
        actualCents: 17200,
        dueDay: 15,
        verified: false,
        sortOrder: 2,
        metadata: { recurring: true },
      },
      {
        id: "groceries",
        section: "variable",
        category: "Food",
        name: "Groceries",
        budgetCents: 65000,
        actualCents: 42000,
        verified: false,
        sortOrder: 3,
      },
      {
        id: "visa",
        section: "credit",
        category: "Debt",
        name: "Visa",
        budgetCents: 20000,
        actualCents: 20000,
        dueDay: 18,
        verified: false,
        sortOrder: 4,
        metadata: {
          limitCents: 600000,
          balanceCents: 142000,
          minimumPaymentCents: 6500,
        },
      },
      {
        id: "auto",
        section: "loan",
        category: "Debt",
        name: "Auto loan",
        budgetCents: 41000,
        actualCents: 41000,
        dueDay: 22,
        verified: true,
        sortOrder: 5,
        metadata: { balanceCents: 980000, minimumPaymentCents: 41000 },
      },
      {
        id: "emergency",
        section: "envelope",
        category: "Savings",
        name: "Emergency fund",
        budgetCents: 30000,
        actualCents: 125000,
        verified: true,
        sortOrder: 6,
        metadata: { goalCents: 500000 },
      },
    ],
    variableEntries: [
      {
        id: "coffee",
        category: "Food",
        amountCents: 1200,
        spentAt: `${monthKey}-08`,
        note: "Coffee",
      },
      {
        id: "gas",
        category: "Transport",
        amountCents: 5400,
        spentAt: `${monthKey}-12`,
        note: "Gas",
      },
    ],
  };
}
